uffd/models/role.py
from sqlalchemy import Column, String, Integer, Text, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.orm.collections import MappedCollection, collection

from uffd.database import db
from .user import User

class RoleGroup(db.Model):
	__tablename__ = 'role_groups'
	role_id = Column(Integer(), ForeignKey('role.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
	role = relationship('Role', back_populates='groups')
	group_id = Column(Integer(), ForeignKey('group.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
	group = relationship('Group')
	requires_mfa = Column(Boolean(create_constraint=True), default=False, nullable=False)

# pylint: disable=E1101
role_members = db.Table('role_members',
	db.Column('role_id', db.Integer(), db.ForeignKey('role.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True),
	db.Column('user_id', db.Integer(), db.ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
)

# pylint: disable=E1101
role_inclusion = db.Table('role-inclusion',
	Column('role_id', Integer, ForeignKey('role.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True),
	Column('included_role_id', Integer, ForeignKey('role.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
)

def flatten_recursive(objs, attr):
	'''Returns a set of objects and all objects included in object.`attr` recursivly while avoiding loops'''
	objs = set(objs)
	new_objs = set(objs)
	while new_objs:
		for obj in getattr(new_objs.pop(), attr):
			if obj not in objs:
				objs.add(obj)
				new_objs.add(obj)
	return objs

def get_user_roles_effective(user):
	base = set(user.roles)
	if not user.is_service_user:
		base.update(Role.query.filter_by(is_default=True))
	return flatten_recursive(base, 'included_roles')

User.roles_effective = property(get_user_roles_effective)

def compute_user_groups(user, ignore_mfa=False):
	groups = set()
	for role in user.roles_effective:
		for group in role.groups:
			if ignore_mfa or not role.groups[group].requires_mfa or user.mfa_enabled:
				groups.add(group)
	return groups

User.compute_groups = compute_user_groups

def update_user_groups(user):
	current_groups = set(user.groups)
	groups = user.compute_groups()
	if groups == current_groups:
		return set(), set()
	groups_added = groups - current_groups
	groups_removed = current_groups - groups
	for group in groups_removed:
		user.groups.remove(group)
	for group in groups_added:
		user.groups.append(group)
	return groups_added, groups_removed

User.update_groups = update_user_groups

class RoleGroupMap(MappedCollection):
	def __init__(self):
		super().__init__(keyfunc=lambda rolegroup: rolegroup.group)

	@collection.internally_instrumented
	def __setitem__(self, key, value, _sa_initiator=None):
		value.group = key
		super().__setitem__(key, value, _sa_initiator)

class Role(db.Model):
	__tablename__ = 'role'
	id = Column(Integer(), primary_key=True, autoincrement=True)
	name = Column(String(32), unique=True, nullable=False)
	description = Column(Text(), default='', nullable=False)
	included_roles = relationship('Role', secondary=role_inclusion,
	                               primaryjoin=id == role_inclusion.c.role_id,
	                               secondaryjoin=id == role_inclusion.c.included_role_id,
																 backref='including_roles')
	including_roles = [] # overwritten by backref

	moderator_group_id = Column(Integer(), ForeignKey('group.id', onupdate='CASCADE', ondelete='SET NULL'), nullable=True)
	moderator_group = relationship('Group')

	members = relationship('User', secondary='role_members', back_populates='roles')

	groups = relationship('RoleGroup', collection_class=RoleGroupMap, cascade='all, delete-orphan', back_populates='role')

	# Roles that are managed externally (e.g. by Ansible) can be locked to
	# prevent accidental editing of name, moderator group, included roles
	# and groups as well as deletion in the web interface.
	locked = Column(Boolean(create_constraint=True), default=False, nullable=False)

	is_default = Column(Boolean(create_constraint=True), default=False, nullable=False)

	@property
	def members_effective(self):
		members = set()
		for role in flatten_recursive([self], 'including_roles'):
			members.update(role.members)
			if role.is_default:
				members.update([user for user in User.query.all() if not user.is_service_user])
		return members

	@property
	def included_roles_recursive(self):
		return flatten_recursive(self.included_roles, 'included_roles')

	@property
	def groups_effective(self):
		groups = set(self.groups)
		for role in self.included_roles_recursive:
			groups.update(role.groups)
		return groups

	def update_member_groups(self):
		for user in self.members_effective:
			user.update_groups()

uffd/user/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, current_app

from uffd.navbar import register_navbar
from uffd.csrf import csrf_protect
from uffd.selfservice import send_passwordreset
from uffd.ldap import get_conn, escape_filter_chars
from uffd.session import login_required, is_valid_session, get_current_user

from .models import User, Group

bp_user = Blueprint("user", __name__, template_folder='templates', url_prefix='/user/')
@bp_user.before_request
@login_required()
def user_acl(): #pylint: disable=inconsistent-return-statements
	if not user_acl_check():
		flash('Access denied')
		return redirect(url_for('index'))

def user_acl_check():
	return is_valid_session() and get_current_user().is_in_group(current_app.config['ACL_ADMIN_GROUP'])

@bp_user.route("/")
@register_navbar('Users', icon='users', blueprint=bp_user, visible=user_acl_check)
def user_list():
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_USER"], '(objectclass=person)')
	users = []
	for i in conn.entries:
		users.append(User.from_ldap(i))
	return render_template('user_list.html', users=users)

@bp_user.route("/<int:uid>")
@bp_user.route("/new")
def user_show(uid=None):
	if not uid:
		user = User()
		ldif = '<none yet>'
	else:
		conn = get_conn()
		conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
		assert len(conn.entries) == 1
		user = User.from_ldap(conn.entries[0])
		ldif = conn.entries[0].entry_to_ldif()
	return render_template('user.html', user=user, user_ldif=ldif)

@bp_user.route("/<int:uid>/update", methods=['POST'])
@bp_user.route("/new", methods=['POST'])
@csrf_protect(blueprint=bp_user)
def user_update(uid=False):
	conn = get_conn()
	is_newuser = bool(not uid)
	if is_newuser:
		user = User()
		if not user.set_loginname(request.form['loginname']):
			flash('Login name does not meet requirements')
			return redirect(url_for('.user_show'))
	else:
		conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
		assert len(conn.entries) == 1
		user = User.from_ldap(conn.entries[0])
	if not user.set_mail(request.form['mail']):
		flash('Mail is invalide.')
		return redirect(url_for('.user_show'))
	new_displayname = request.form['displayname'] if request.form['displayname'] else request.form['loginname']
	if not user.set_displayname(new_displayname):
		flash('Display name does not meet requirements')
		return redirect(url_for('.user_show'))
	new_password = request.form.get('password')
	if new_password and not is_newuser:
		user.set_password(new_password)
	if user.to_ldap(new=is_newuser):
		if is_newuser:
			send_passwordreset(user.loginname)
			flash('User created. We sent the user a password reset link by mail')
		else:
			flash('User updated')
	else:
		flash('Error updating user: {}'.format(conn.result['message']))
	return redirect(url_for('.user_list'))

@bp_user.route("/<int:uid>/del")
@csrf_protect(blueprint=bp_user)
def user_delete(uid):
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
	assert len(conn.entries) == 1
	if conn.delete(conn.entries[0].entry_dn):
		flash('Deleted user')
	else:
		flash('Could not delete user: {}'.format(conn.result['message']))
	return redirect(url_for('.user_list'))

bp_group = Blueprint("group", __name__, template_folder='templates', url_prefix='/group/')
@bp_group.before_request
@login_required()
def group_acl(): #pylint: disable=inconsistent-return-statements
	if not user_acl_check():
		flash('Access denied')
		return redirect(url_for('index'))

@bp_group.route("/")
@register_navbar('Groups', icon='layer-group', blueprint=bp_group, visible=user_acl_check)
def group_list():
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_GROUPS"], '(objectclass=groupOfUniqueNames)')
	groups = []
	for i in conn.entries:
		groups.append(Group.from_ldap(i))
	return render_template('group_list.html', groups=groups)

@bp_group.route("/<int:gid>")
def group_show(gid):
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_GROUPS"], '(&(objectclass=groupOfUniqueNames)(gidNumber={}))'.format((escape_filter_chars(gid))))
	assert len(conn.entries) == 1
	group = Group.from_ldap(conn.entries[0])
	return render_template('group.html', group=group)

uffd/views/role.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, current_app
from flask_babel import gettext as _, lazy_gettext

from uffd.navbar import register_navbar
from uffd.csrf import csrf_protect
from uffd.database import db
from uffd.models import Role, RoleGroup, Group
from .session import login_required

bp = Blueprint("role", __name__, template_folder='templates', url_prefix='/role/')

def role_acl_check():
	return request.user and request.user.is_in_group(current_app.config['ACL_ADMIN_GROUP'])

@bp.before_request
@login_required(role_acl_check)
def role_acl():
	pass

@bp.route("/")
@register_navbar(lazy_gettext('Roles'), icon='key', blueprint=bp, visible=role_acl_check)
def index():
	return render_template('role/list.html', roles=Role.query.all())

@bp.route("/new")
def new():
	return render_template('role/show.html', role=Role(), groups=Group.query.all(), roles=Role.query.all())

@bp.route("/<int:roleid>")
def show(roleid=None):
	role = Role.query.get(roleid)
	return render_template('role/show.html', role=role, groups=Group.query.all(), roles=Role.query.all())

@bp.route("/<int:roleid>/update", methods=['POST'])
@bp.route("/new", methods=['POST'])
@csrf_protect(blueprint=bp)
def update(roleid=None):
	if roleid is None:
		role = Role()
		db.session.add(role)
	else:
		role = Role.query.get(roleid)
	role.description = request.values['description']
	if not role.locked:
		role.name = request.values['name']
		if not request.values['moderator-group']:
			role.moderator_group = None
		else:
			role.moderator_group = Group.query.get(request.values['moderator-group'])
		for included_role in Role.query.all():
			if included_role != role and request.values.get('include-role-{}'.format(included_role.id)):
				role.included_roles.append(included_role)
			elif included_role in role.included_roles:
				role.included_roles.remove(included_role)
		role.groups.clear()
		for group in Group.query.all():
			if request.values.get(f'group-{group.id}', False):
				role.groups[group] = RoleGroup(requires_mfa=bool(request.values.get(f'group-mfa-{group.id}', '')))
	role.update_member_groups()
	db.session.commit()
	return redirect(url_for('role.show', roleid=role.id))

@bp.route("/<int:roleid>/del")
@csrf_protect(blueprint=bp)
def delete(roleid):
	role = Role.query.get(roleid)
	if role.locked:
		flash(_('Locked roles cannot be deleted'))
		return redirect(url_for('role.show', roleid=role.id))
	old_members = set(role.members_effective)
	role.members.clear()
	db.session.delete(role)
	for user in old_members:
		user.update_groups()
	db.session.commit()
	return redirect(url_for('role.index'))

@bp.route("/<int:roleid>/unlock")
@csrf_protect(blueprint=bp)
def unlock(roleid):
	role = Role.query.get(roleid)
	role.locked = False
	db.session.commit()
	return redirect(url_for('role.show', roleid=role.id))

@bp.route("/<int:roleid>/setdefault")
@csrf_protect(blueprint=bp)
def set_default(roleid):
	role = Role.query.get(roleid)
	if role.is_default:
		return redirect(url_for('role.show', roleid=role.id))
	role.is_default = True
	for user in set(role.members):
		if not user.is_service_user:
			role.members.remove(user)
	role.update_member_groups()
	db.session.commit()
	return redirect(url_for('role.show', roleid=role.id))

@bp.route("/<int:roleid>/unsetdefault")
@csrf_protect(blueprint=bp)
def unset_default(roleid):
	role = Role.query.get(roleid)
	if not role.is_default:
		return redirect(url_for('role.show', roleid=role.id))
	old_members = set(role.members_effective)
	role.is_default = False
	for user in old_members:
		if not user.is_service_user:
			user.update_groups()
	db.session.commit()
	return redirect(url_for('role.show', roleid=role.id))

uffd/templates/role/list.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
	<div class="col">
		<p class="text-right">
			<a class="btn btn-primary" href="{{ url_for("role.new") }}">
				<i class="fa fa-plus" aria-hidden="true"></i> {{_("New")}}
			</a>
		</p>
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">{{_("Name")}}</th>
					<th scope="col">{{_("Description")}}</th>
				</tr>
			</thead>
			<tbody>
				{% for role in roles|sort(attribute="name") %}
				<tr id="role-{{ role.id }}">
					<th scope="row">
						<a href="{{ url_for("role.show", roleid=role.id) }}">
							{{ role.name or _('<empty name>') }}
						</a>
					</th>
					<td>
						{{ role.description }}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

uffd/templates/role/show.html
{% extends 'base.html' %}

{% block body %}
{% if role.locked %}
<div class="alert alert-warning" role="alert">
{{_("Name, moderator group, included roles and groups of this role are managed externally.")}} <a href="{{ url_for("role.unlock", roleid=role.id) }}" class="alert-link">Unlock this role</a> to edit them at the risk of having your changes overwritten.
</div>
{% endif %}

<form action="{{ url_for("role.update", roleid=role.id) }}" method="POST" autocomplete="off">
<div class="align-self-center">
	<div class="clearfix pb-2"><div class="float-sm-right">
		<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{_("Save")}}</button>
		<a href="{{ url_for("role.index") }}" class="btn btn-secondary">{{_("Cancel")}}</a>
		{% if role.id %}
			{% if not role.is_default %}
			<a href="{{ url_for("role.set_default", roleid=role.id) }}" onClick='return confirm({{_("All non-service users will be removed as members from this role and get its permissions implicitly. Are you sure?")|tojson}});' class="btn btn-secondary">{{_("Set as default")}}</a>
			{% else %}
			<a href="{{ url_for("role.unset_default", roleid=role.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});' class="btn btn-secondary">{{_("Unset as default")}}</a>
			{% endif %}
			<a href="{{ url_for("role.delete", roleid=role.id) }}"  onClick='return confirm({{_("Are you sure?")|tojson}});' class="btn btn-danger {{ 'disabled' if role.locked }}"><i class="fa fa-trash" aria-hidden="true"></i> {{_("Delete")}}</a>
		{% else %}
			<a href="#" class="btn btn-secondary disabled">{{_("Set as default")}}</a>
			<a href="#" class="btn btn-danger disabled"><i class="fa fa-trash" aria-hidden="true"></i> {{_("Delete")}}</a>
		{% endif %}
	</div></div>
	<ul class="nav nav-tabs pt-2 border-0" id="tablist" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="true">{{_("Settings")}}</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="roles-tab" data-toggle="tab" href="#roles" role="tab" aria-controls="roles" aria-selected="false">{{_("Included roles")}} <span class="badge badge-pill badge-secondary">{{ role.included_roles|length }}</span></a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="groups-tab" data-toggle="tab" href="#groups" role="tab" aria-controls="groups" aria-selected="false">{{_("Included groups")}} <span class="badge badge-pill badge-secondary">{{ role.groups|length }}</span></a>
		</li>
	</ul>

	<div class="tab-content border mb-2 pt-2" id="tabcontent">
		<div class="tab-pane fade show active" id="settings" role="tabpanel" aria-labelledby="settings-tab">
			<div class="form-group col">
				<label for="role-name">{{_("Role Name")}}</label>
				<input type="text" class="form-control" id="role-name" name="name" value="{{ role.name or '' }}" {{ 'disabled' if role.locked }}>
				<small class="form-text text-muted">
				</small>
			</div>
			<div class="form-group col">
				<label for="role-description">{{_("Description")}}</label>
				<textarea class="form-control" id="role-description" name="description" rows="5">{{ role.description or '' }}</textarea>
				<small class="form-text text-muted">
				</small>
			</div>
			<div class="form-group col">
				<label for="moderator-group">{{_("Moderator Group")}}</label>
				<select class="form-control" id="moderator-group" name="moderator-group" {{ 'disabled' if role.locked }}>
					<option value="" class="text-muted">{{_("No Moderator Group")}}</option>
					{% for group in groups %}
					<option value="{{ group.id }}" {{ 'selected' if group == role.moderator_group }}>{{ group.name }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group col">
				<span>{{_("Moderators")}}:</span>
				<ul class="row">
					{% for moderator in role.moderator_group.members %}
					<li class="col-12 col-xs-6 col-sm-4 col-md-3 col-lg-2"><a href="{{ url_for("user.show", id=moderator.id) }}">{{ moderator.loginname }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<div class="form-group col">
				<span>{{_("Members")}}:</span>
				<ul class="row">
				{% for member in role.members|sort(attribute='loginname') %}
					<li class="col-12 col-xs-6 col-sm-4 col-md-3 col-lg-2"><a href="{{ url_for("user.show", id=member.id) }}">{{ member.loginname }}</a></li>
				{% endfor %}
				</ul>
			</div>
		</div>
		<div class="tab-pane fade" id="roles" role="tabpanel" aria-labelledby="roles-tab">
			<div class="form-group col">
				<span>{{_("Roles to include groups from recursively")}}</span>
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th scope="col"></th>
							<th scope="col">{{_("name")}}</th>
							<th scope="col">{{_("description")}}</th>
							<th scope="col">{{_("currently includes groups")}}</th>
						</tr>
					</thead>
					<tbody>
						{% for r in roles|sort(attribute="name")|sort(attribute='name') %}
						<tr id="include-role-{{ r.id }}">
							<td>
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="include-role-{{ r.id }}-checkbox" name="include-role-{{ r.id }}" value="1" aria-label="enabled"
										{% if r == role or role.locked %} disabled{% endif %}
										{% if r in role.included_roles %} checked{% endif %}>
								</div>
							</td>
							<td>
								<a href="{{ url_for("role.show", roleid=r.id) }}">
									{{ r.name }}
								</a>
							</td>
							<td>
								{{ r.description }}
							</td>
							<td>
								{% for group in r.groups_effective|sort(attribute='name') %}
									<a href="{{ url_for("group.show", id=group.id) }}">{{ group.name }}</a>{{ ', ' if not loop.last }}
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		<div class="tab-pane fade" id="groups" role="tabpanel" aria-labelledby="groups-tab">
			<div class="form-group col">
				<span>{{_("Included groups")}}</span>
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th scope="col"></th>
							<th scope="col">{{_("name")}}</th>
							<th scope="col">{{_("description")}}</th>
							<th scope="col">{{_("2FA required")}}</th>
						</tr>
					</thead>
					<tbody>
						{% for group in groups|sort(attribute="name") %}
						<tr id="group-{{ group.id }}">
							<td>
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="group-{{ group.id }}-checkbox" name="group-{{ group.id }}" value="1" aria-label="enabled" {% if group in role.groups %}checked{% endif %} {{ 'disabled' if role.locked }}>
								</div>
							</td>
							<td>
								<a href="{{ url_for("group.show", id=group.id) }}">
									{{ group.name }}
								</a>
							</td>
							<td>
								{{ group.description }}
							</td>
							<td>
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="group-mfa-{{ group.id }}-checkbox" name="group-mfa-{{ group.id }}" value="1" aria-label="enabled" {% if group in role.groups and role.groups[group].requires_mfa %}checked{% endif %} {{ 'disabled' if role.locked }}>
								</div>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
</form>
{% endblock %}