uffd/api/models.py
from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, Text
from sqlalchemy.orm import relationship

from uffd.database import db
from uffd.password_hash import PasswordHashAttribute, HighEntropyPasswordHash

class APIClient(db.Model):
	__tablename__ = 'api_client'
	id = Column(Integer, primary_key=True, autoincrement=True)
	service_id = Column(Integer, ForeignKey('service.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
	service = relationship('Service', back_populates='api_clients')
	auth_username = Column(String(40), unique=True, nullable=False)
	_auth_password = Column('auth_password', Text(), nullable=False)
	auth_password = PasswordHashAttribute('_auth_password', HighEntropyPasswordHash)

	# Permissions are defined by adding an attribute named "perm_NAME"
	perm_users = Column(Boolean(), default=False, nullable=False)
	perm_checkpassword = Column(Boolean(), default=False, nullable=False)
	perm_mail_aliases = Column(Boolean(), default=False, nullable=False)
	perm_remailer = Column(Boolean(), default=False, nullable=False)

	@classmethod
	def permission_exists(cls, name):
		return hasattr(cls, 'perm_'+name)

	def has_permission(self, name):
		return getattr(self, 'perm_' + name)

uffd/models/api.py
from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, Text
from sqlalchemy.orm import relationship

from uffd.database import db
from uffd.password_hash import PasswordHashAttribute, HighEntropyPasswordHash

class APIClient(db.Model):
	__tablename__ = 'api_client'
	id = Column(Integer, primary_key=True, autoincrement=True)
	service_id = Column(Integer, ForeignKey('service.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
	service = relationship('Service', back_populates='api_clients')
	auth_username = Column(String(40), unique=True, nullable=False)
	_auth_password = Column('auth_password', Text(), nullable=False)
	auth_password = PasswordHashAttribute('_auth_password', HighEntropyPasswordHash)

	# Permissions are defined by adding an attribute named "perm_NAME"
	perm_users = Column(Boolean(create_constraint=True), default=False, nullable=False)
	perm_checkpassword = Column(Boolean(create_constraint=True), default=False, nullable=False)
	perm_mail_aliases = Column(Boolean(create_constraint=True), default=False, nullable=False)
	perm_remailer = Column(Boolean(create_constraint=True), default=False, nullable=False)
	perm_metrics = Column(Boolean(create_constraint=True), default=False, nullable=False)

	@classmethod
	def permission_exists(cls, name):
		return hasattr(cls, 'perm_'+name)

	def has_permission(self, name):
		return getattr(self, 'perm_' + name)

uffd/services/views.py
from flask import Blueprint, render_template, current_app, abort, request
from flask_babel import lazy_gettext, get_locale

from uffd.navbar import register_navbar

bp = Blueprint("services", __name__, template_folder='templates', url_prefix='/services')

# pylint: disable=too-many-branches
def get_services(user=None):
	if not user and not current_app.config['SERVICES_PUBLIC']:
		return []
	services = []
	for service_data in current_app.config['SERVICES']:
		service_title = get_language_specific(service_data, 'title')
		if not service_title:
			continue
		service_description = get_language_specific(service_data, 'description')
		service = {
			'title': service_title,
			'subtitle': service_data.get('subtitle', ''),
			'description': service_description,
			'url': service_data.get('url', ''),
			'logo_url': service_data.get('logo_url', ''),
			'has_access': True,
			'permission': '',
			'groups': [],
			'infos': [],
			'links': [],
		}
		if service_data.get('required_group'):
			if not user or not user.has_permission(service_data['required_group']):
				service['has_access'] = False
		for permission_data in service_data.get('permission_levels', []):
			if permission_data.get('required_group'):
				if not user or not user.has_permission(permission_data['required_group']):
					continue
			if not permission_data.get('name'):
				continue
			service['has_access'] = True
			service['permission'] = permission_data['name']
		if service_data.get('confidential', False) and not service['has_access']:
			continue
		for group_data in service_data.get('groups', []):
			if group_data.get('required_group'):
				if not user or not user.has_permission(group_data['required_group']):
					continue
			if not group_data.get('name'):
				continue
			service['groups'].append(group_data)
		for info_data in service_data.get('infos', []):
			if info_data.get('required_group'):
				if not user or not user.has_permission(info_data['required_group']):
					continue
			info_title = get_language_specific(info_data, 'title')
			info_html = get_language_specific(info_data, 'html')
			if not info_title or not info_html:
				continue
			info_button_text = get_language_specific(info_data, 'button_text', info_title)
			info = {
				'title': info_title,
				'button_text': info_button_text,
				'html': info_html,
				'id': '%d-%d'%(len(services), len(service['infos'])),
			}
			service['infos'].append(info)
		for link_data in service_data.get('links', []):
			if link_data.get('required_group'):
				if not user or not user.has_permission(link_data['required_group']):
					continue
			if not link_data.get('url') or not link_data.get('title'):
				continue
			service['links'].append(link_data)
		services.append(service)
	return services

def get_language_specific(data, field_name, default =''):
	return data.get(field_name + '_' + get_locale().language, data.get(field_name, default))

def services_visible():
	return len(get_services(request.user)) > 0

@bp.route("/")
@register_navbar(lazy_gettext('Services'), icon='sitemap', blueprint=bp, visible=services_visible)
def index():
	services = get_services(request.user)
	if not current_app.config['SERVICES']:
		abort(404)

	banner = current_app.config.get('SERVICES_BANNER')

	# Set the banner to None if it is not public and no user is logged in
	if not (current_app.config["SERVICES_BANNER_PUBLIC"] or request.user):
		banner = None

	return render_template('services/overview.html', user=request.user, services=services, banner=banner)

uffd/views/service.py
import functools

from flask import Blueprint, render_template, request, url_for, redirect, current_app, abort
from flask_babel import lazy_gettext

from uffd.navbar import register_navbar
from uffd.csrf import csrf_protect
from uffd.database import db
from uffd.models import User, Service, ServiceUser, get_services, Group, OAuth2Client, OAuth2LogoutURI, APIClient, RemailerMode

from .session import login_required

bp = Blueprint('service', __name__, template_folder='templates')

bp.add_app_template_global(RemailerMode, 'RemailerMode')

def admin_acl():
	return request.user and request.user.is_in_group(current_app.config['ACL_ADMIN_GROUP'])

def overview_login_maybe_required(func):
	@functools.wraps(func)
	def decorator(*args, **kwargs):
		if not current_app.config['SERVICES']:
			return login_required(admin_acl)(func)(*args, **kwargs)
		if not current_app.config['SERVICES_PUBLIC']:
			return login_required()(func)(*args, **kwargs)
		return func(*args, **kwargs)
	return decorator

def overview_navbar_visible():
	return get_services(request.user) or admin_acl()

@bp.route('/services/')
@register_navbar(lazy_gettext('Services'), icon='sitemap', blueprint=bp, visible=overview_navbar_visible)
@overview_login_maybe_required
def overview():
	services = get_services(request.user)
	banner = ''
	if request.user or current_app.config['SERVICES_BANNER_PUBLIC']:
		banner = current_app.config['SERVICES_BANNER']
	return render_template('service/overview.html', services=services, banner=banner)

@bp.route('/service/admin')
@login_required(admin_acl)
def index():
	return render_template('service/index.html', services=Service.query.all())

@bp.route('/service/new')
@bp.route('/service/<int:id>')
@login_required(admin_acl)
def show(id=None):
	service = Service() if id is None else Service.query.get_or_404(id)
	remailer_overwrites = []
	if id is not None:
		# pylint: disable=singleton-comparison
		remailer_overwrites = ServiceUser.query.filter(
			ServiceUser.service_id == id,
			ServiceUser.remailer_overwrite_mode != None
		).all()
	all_groups = Group.query.all()
	return render_template('service/show.html', service=service, all_groups=all_groups, remailer_overwrites=remailer_overwrites)

@bp.route('/service/new', methods=['POST'])
@bp.route('/service/<int:id>', methods=['POST'])
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def edit_submit(id=None):
	if id is None:
		service = Service()
		db.session.add(service)
	else:
		service = Service.query.get_or_404(id)
	service.name = request.form['name']
	if not request.form['access-group']:
		service.limit_access = True
		service.access_group = None
	elif request.form['access-group'] == 'all':
		service.limit_access = False
		service.access_group = None
	else:
		service.limit_access = True
		service.access_group = Group.query.get(request.form['access-group'])
	service.hide_deactivated_users = request.form.get('hide_deactivated_users') == '1'
	service.enable_email_preferences = request.form.get('enable_email_preferences') == '1'
	service.remailer_mode = RemailerMode[request.form['remailer-mode']]
	remailer_overwrite_mode = RemailerMode[request.form['remailer-overwrite-mode']]
	remailer_overwrite_user_ids = [
		User.query.filter_by(loginname=loginname.strip()).one().id
		for loginname in request.form['remailer-overwrite-users'].split(',') if loginname.strip()
	]
	# pylint: disable=singleton-comparison
	service_users = ServiceUser.query.filter(
		ServiceUser.service == service,
		db.or_(
			ServiceUser.user_id.in_(remailer_overwrite_user_ids),
			ServiceUser.remailer_overwrite_mode != None,
		)
	)
	for service_user in service_users:
		if service_user.user_id in remailer_overwrite_user_ids:
			service_user.remailer_overwrite_mode = remailer_overwrite_mode
		else:
			service_user.remailer_overwrite_mode = None
	db.session.commit()
	return redirect(url_for('service.show', id=service.id))

@bp.route('/service/<int:id>/delete')
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def delete(id):
	service = Service.query.get_or_404(id)
	db.session.delete(service)
	db.session.commit()
	return redirect(url_for('service.index'))

@bp.route('/service/<int:service_id>/oauth2/new')
@bp.route('/service/<int:service_id>/oauth2/<int:db_id>')
@login_required(admin_acl)
def oauth2_show(service_id, db_id=None):
	service = Service.query.get_or_404(service_id)
	client = OAuth2Client() if db_id is None else OAuth2Client.query.filter_by(service_id=service_id, db_id=db_id).first_or_404()
	return render_template('service/oauth2.html', service=service, client=client)

@bp.route('/service/<int:service_id>/oauth2/new', methods=['POST'])
@bp.route('/service/<int:service_id>/oauth2/<int:db_id>', methods=['POST'])
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def oauth2_submit(service_id, db_id=None):
	service = Service.query.get_or_404(service_id)
	if db_id is None:
		client = OAuth2Client(service=service)
		db.session.add(client)
	else:
		client = OAuth2Client.query.filter_by(service_id=service_id, db_id=db_id).first_or_404()
	client.client_id = request.form['client_id']
	if request.form['client_secret']:
		client.client_secret = request.form['client_secret']
	if not client.client_secret:
		abort(400)
	client.redirect_uris = [x.strip() for x in request.form['redirect_uris'].split('\n') if x.strip()]
	client.logout_uris = []
	for line in request.form['logout_uris'].split('\n'):
		line = line.strip()
		if not line:
			continue
		method, uri = line.split(' ', 2)
		client.logout_uris.append(OAuth2LogoutURI(method=method, uri=uri))
	db.session.commit()
	return redirect(url_for('service.show', id=service.id))

@bp.route('/service/<int:service_id>/oauth2/<int:db_id>/delete')
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def oauth2_delete(service_id, db_id=None):
	service = Service.query.get_or_404(service_id)
	client = OAuth2Client.query.filter_by(service_id=service_id, db_id=db_id).first_or_404()
	db.session.delete(client)
	db.session.commit()
	return redirect(url_for('service.show', id=service.id))

@bp.route('/service/<int:service_id>/api/new')
@bp.route('/service/<int:service_id>/api/<int:id>')
@login_required(admin_acl)
def api_show(service_id, id=None):
	service = Service.query.get_or_404(service_id)
	client = APIClient() if id is None else APIClient.query.filter_by(service_id=service_id, id=id).first_or_404()
	return render_template('service/api.html', service=service, client=client)

@bp.route('/service/<int:service_id>/api/new', methods=['POST'])
@bp.route('/service/<int:service_id>/api/<int:id>', methods=['POST'])
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def api_submit(service_id, id=None):
	service = Service.query.get_or_404(service_id)
	if id is None:
		client = APIClient(service=service)
		db.session.add(client)
	else:
		client = APIClient.query.filter_by(service_id=service_id, id=id).first_or_404()
	client.auth_username = request.form['auth_username']
	if request.form['auth_password']:
		client.auth_password = request.form['auth_password']
	if not client.auth_password:
		abort(400)
	client.perm_users = request.form.get('perm_users') == '1'
	client.perm_checkpassword = request.form.get('perm_checkpassword') == '1'
	client.perm_mail_aliases = request.form.get('perm_mail_aliases') == '1'
	client.perm_remailer = request.form.get('perm_remailer') == '1'
	client.perm_metrics = request.form.get('perm_metrics') == '1'
	db.session.commit()
	return redirect(url_for('service.show', id=service.id))

@bp.route('/service/<int:service_id>/api/<int:id>/delete')
@csrf_protect(blueprint=bp)
@login_required(admin_acl)
def api_delete(service_id, id=None):
	service = Service.query.get_or_404(service_id)
	client = APIClient.query.filter_by(service_id=service_id, id=id).first_or_404()
	db.session.delete(client)
	db.session.commit()
	return redirect(url_for('service.show', id=service.id))

uffd/templates/service/api.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
	<form action="{{ url_for('service.api_submit', service_id=service.id, id=client.id) }}" method="POST" autocomplete="off" class="form col-12 px-0">

		<div class="form-group col">
			<p class="text-right">
				<a href="{{ url_for('service.show', id=service.id) }}" class="btn btn-secondary">{{ _('Cancel') }}</a>
				{% if client.id %}
				<a class="btn btn-danger" href="{{ url_for('service.api_delete', service_id=service.id, id=client.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});'>
					<i class="fa fa-trash" aria-hidden="true"></i> {{_('Delete')}}
				</a>
				{% endif %}
				<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{ _('Save') }}</button>
			</p>
		</div>

		<div class="form-group col">
			<label for="client-auth-username">{{ _('Authentication Username') }}</label>
			<input type="text" class="form-control" id="client-auth-username" name="auth_username" value="{{ client.auth_username or '' }}" required>
		</div>

		<div class="form-group col">
			<label for="client-auth-password">{{ _('Authentication Password') }}</label>
			{% if client.id %}
			<input type="password" autocomplete="new-password" class="form-control" id="client-auth-password" name="auth_password" placeholder="●●●●●●●●">
			{% else %}
			<input type="password" autocomplete="new-password" class="form-control" id="client-auth-password" name="auth_password" required>
			{% endif %}
		</div>

		<div class="form-group col">
			<h6>{{ _('Permissions') }}</h6>
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="client-perm-users" name="perm_users" value="1" aria-label="enabled" {{ 'checked' if client.perm_users }}>
				<label class="form-check-label" for="client-perm-users"><b>users</b>: {{_('Access user and group data')}}</label>
			</div>
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="client-perm-checkpassword" name="perm_checkpassword" value="1" aria-label="enabled" {{ 'checked' if client.perm_checkpassword }}>
				<label class="form-check-label" for="client-perm-checkpassword"><b>checkpassword</b>: {{_('Verify user passwords')}}</label>
			</div>
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="client-perm-mail-aliases" name="perm_mail_aliases" value="1" aria-label="enabled" {{ 'checked' if client.perm_mail_aliases }}>
				<label class="form-check-label" for="client-perm-mail-aliases"><b>mail_aliases</b>: {{_('Access mail aliases')}}</label>
			</div>
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="client-perm-remailer" name="perm_remailer" value="1" aria-label="enabled" {{ 'checked' if client.perm_remailer }}>
				<label class="form-check-label" for="client-perm-remailer"><b>remailer</b>: {{_('Resolve remailer addresses')}}</label>
				{% if not remailer.configured %}
				<i class="fas fa-exclamation-triangle text-warning" data-toggle="tooltip" data-placement="top" title="{{ _('This option has no effect: Remailer config options are unset') }}"></i>
				{% endif %}
			</div>
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="client-perm-metrics" name="perm_metrics" value="1" aria-label="enabled" {{ 'checked' if client.perm_metrics }}>
				<label class="form-check-label" for="client-perm-metrics"><b>metrics</b>: {{_('Access uffd metrics')}}</label>
			</div>
		</div>

	</form>
</div>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

uffd/templates/service/index.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
	<div class="col">
		<p class="text-right">
			<a class="btn btn-primary" href="{{ url_for('service.show') }}">
				<i class="fa fa-plus" aria-hidden="true"></i> {{_("New")}}
			</a>
		</p>
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">{{ _('Name') }}</th>
				</tr>
			</thead>
			<tbody>
				{% for service in services|sort(attribute="name") %}
				<tr>
					<td>
						<a href="{{ url_for("service.show", id=service.id) }}">
							{{ service.name }}
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

uffd/templates/service/oauth2.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
	<form action="{{ url_for('service.oauth2_submit', service_id=service.id, db_id=client.db_id) }}" method="POST" autocomplete="off" class="form col-12 px-0">

		<div class="form-group col">
			<p class="text-right">
				<a href="{{ url_for('service.show', id=service.id) }}" class="btn btn-secondary">{{ _('Cancel') }}</a>
				{% if client.db_id %}
				<a class="btn btn-danger" href="{{ url_for('service.oauth2_delete', service_id=service.id, db_id=client.db_id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});'>
					<i class="fa fa-trash" aria-hidden="true"></i> {{_('Delete')}}
				</a>
				{% endif %}
				<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{ _('Save') }}</button>
			</p>
		</div>

		<div class="form-group col">
			<label for="client-client-id">{{ _('Client ID') }}</label>
			<input type="text" class="form-control" id="client-client-id" name="client_id" value="{{ client.client_id or '' }}" required>
		</div>

		<div class="form-group col">
			<label for="client-client-secret">{{ _('Client Secret') }}</label>
			{% if client.db_id %}
			<input type="password" autocomplete="new-password" class="form-control" id="client-client-secret" name="client_secret" placeholder="●●●●●●●●">
			{% else %}
			<input type="password" autocomplete="new-password" class="form-control" id="client-client-secret" name="client_secret" required>
			{% endif %}
		</div>

		<div class="form-group col">
			<label for="client-redirect-uris">{{ _('Redirect URIs') }}</label>
			<textarea rows="3" class="form-control" id="client-redirect-uris" name="redirect_uris">{{ client.redirect_uris|join('\n') }}</textarea>
			<small class="form-text text-muted">
				{{ _('One URI per line') }}
			</small>
		</div>

		<div class="form-group col">
			<label for="client-logout-uris">{{ _('Logout URIs') }}</label>
			<textarea rows="3" class="form-control" id="client-logout-uris" name="logout_uris" placeholder="GET https://example.com/logout">
{%- for logout_uri in client.logout_uris %}
{{ logout_uri.method }} {{ logout_uri.uri }}{{ '\n' if not loop.last }}
{%- endfor %}
</textarea>
			<small class="form-text text-muted">
				{{ _('One URI per line, prefixed with space-separated method (GET/POST)') }}
			</small>
		</div>

	</form>
</div>
{% endblock %}

uffd/templates/service/show.html
{% extends 'base.html' %}

{% block body %}

<div class="row">

	<form action="{{ url_for('service.edit_submit', id=service.id) }}" method="POST" autocomplete="off" class="form col-12 px-0">
		<div class="form-group col">
			<p class="text-right">
				<a href="{{ url_for('service.index') }}" class="btn btn-secondary">{{ _('Cancel') }}</a>
				{% if service.id %}
				<a class="btn btn-danger" href="{{ url_for('service.delete', id=service.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});'>
					<i class="fa fa-trash" aria-hidden="true"></i> {{_('Delete')}}
				</a>
				{% endif %}
				<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{ _('Save') }}</button>
			</p>
		</div>
		<div class="form-group col">
			<label for="service-name">{{ _('Name') }}</label>
			<input type="text" class="form-control" id="service-name" name="name" value="{{ service.name or '' }}" required>
		</div>
		<div class="form-group col">
			<label for="access-group">{{ _('Access Restriction') }}</label>
			<select class="form-control" id="access-group" name="access-group">
				<option value="" class="text-muted">{{ _('No user has access') }}</option>
				<option value="all" class="text-muted" {{ 'selected' if not service.limit_access }}>{{ _('All users have access (legacy)') }}</option>
				{% for group in all_groups %}
				<option value="{{ group.id }}" {{ 'selected' if group == service.access_group and service.limit_access }}>{{ _('Members of group "%(group_name)s" have access', group_name=group.name) }}</option>
				{% endfor %}
			</select>
		</div>

		<div class="form-group col">
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="hide-deactivated-users" name="hide_deactivated_users" value="1" aria-label="enabled" {{ 'checked' if service.hide_deactivated_users }}>
				<label class="form-check-label" for="hide-deactivated-users">{{ _('Hide deactivated users from service') }}</label>
			</div>
		</div>

		<div class="form-group col">
			<div class="form-check">
				<input class="form-check-input" type="checkbox" id="service-enable-email-preferences" name="enable_email_preferences" value="1" aria-label="enabled" {{ 'checked' if service.enable_email_preferences }}>
				<label class="form-check-label" for="service-enable-email-preferences">{{ _('Allow users with access to select a different e-mail address for this service') }}</label>
			<small class="form-text text-muted">
				{{ _('If disabled, the service always uses the primary e-mail address.') }}
			</small>
			</div>
		</div>

		<div class="form-group col">
			<label for="remailer-mode">
				{{ _('Hide e-mail addresses with remailer') }}
				{% if not remailer.configured and not forwarder.configured %}
				<i class="fas fa-exclamation-triangle text-warning" data-toggle="tooltip" data-placement="top" title="{{ _('This option has no effect: Remailer config options are unset') }}"></i>
				{% endif %}
			</label>
			<select class="form-control" id="remailer-mode" name="remailer-mode">
				<option value="{{ RemailerMode.DISABLED.name }}" {{ 'selected' if service.remailer_mode == RemailerMode.DISABLED }}>
					{{ _('Remailer disabled') }}
				</option>
				<option value="{{ RemailerMode.ENABLED_V2.name }}" {{ 'selected' if service.remailer_mode == RemailerMode.ENABLED_V2 }}>
					{{ _('Remailer enabled') }}
				</option>
				<option value="{{ RemailerMode.ENABLED_V1.name }}" {{ 'selected' if service.remailer_mode == RemailerMode.ENABLED_V1 }}>
					{{ _('Remailer enabled (deprecated, case-sensitive format)') }}
				</option>
				{% if forwarder.configured %}
				<option value="{{ RemailerMode.ENABLED_FORWARDER.name }}" {{ 'selected' if service.remailer_mode == RemailerMode.ENABLED_FORWARDER }}>
					{{ _('Forwarder enabled') }}
				</option>
				{% endif %}
			</select>
			<small class="form-text text-muted">
				{{ _('Some services notify users about changes to their e-mail address. Modifying this setting immediately affects the e-mail addresses of all users and can cause masses of notification e-mails.') }}
			</small>
		</div>

		<div class="form-group col">
			<p class="mb-2">
				{{ _('Overwrite remailer setting for specific users') }}
			</p>
			<div class="input-group" id="remailer-mode-overwrite">
				<input class="form-control" name="remailer-overwrite-users" placeholder="{{ _('Login names') }}" value="{{ remailer_overwrites|map(attribute='user')|map(attribute='loginname')|sort|join(', ') }}">
				<select class="form-control" name="remailer-overwrite-mode">
					{% set remailer_overwrite_mode = remailer_overwrites|map(attribute='remailer_overwrite_mode')|first or RemailerMode.ENABLED_V2 %}
					<option value="{{ RemailerMode.DISABLED.name }}" {{ 'selected' if remailer_overwrite_mode == RemailerMode.DISABLED }}>
						{{ _('Remailer disabled') }}
					</option>
					<option value="{{ RemailerMode.ENABLED_V2.name }}" {{ 'selected' if remailer_overwrite_mode == RemailerMode.ENABLED_V2 }}>
						{{ _('Remailer enabled') }}
					</option>
					<option value="{{ RemailerMode.ENABLED_V1.name }}" {{ 'selected' if remailer_overwrite_mode == RemailerMode.ENABLED_V1 }}>
						{{ _('Remailer enabled (deprecated, case-sensitive format)') }}
					</option>
					{% if forwarder.configured %}
					<option value="{{ RemailerMode.ENABLED_FORWARDER.name }}" {{ 'selected' if remailer_overwrite_mode == RemailerMode.ENABLED_FORWARDER }}>
						{{ _('Forwarder enabled') }}
					</option>
					{% endif %}
				</select>
			</div>
			<small class="form-text text-muted">
				{{ _('Useful for testing remailer before enabling it for all users. Specify users as a comma-seperated list of login names.') }}
			</small>
		</div>

	</form>

	{% if service.id %}
	<div class="col-12">
		<hr>
		<h5>OAuth2 Clients</h5>
		<p class="text-right">
			<a class="btn btn-primary" href="{{ url_for('service.oauth2_show', service_id=service.id) }}">
				<i class="fa fa-plus" aria-hidden="true"></i> {{_("New")}}
			</a>
		</p>
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">{{ _('Client ID') }}</th>
				</tr>
			</thead>
			<tbody>
				{% for client in service.oauth2_clients|sort(attribute='client_id') %}
				<tr>
					<td>
						<a href="{{ url_for("service.oauth2_show", service_id=service.id, db_id=client.db_id) }}">
							{{ client.client_id }}
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	<div class="col-12">
		<hr>
		<h5>API Clients</h5>
		<p class="text-right">
			<a class="btn btn-primary" href="{{ url_for('service.api_show', service_id=service.id) }}">
				<i class="fa fa-plus" aria-hidden="true"></i> {{_("New")}}
			</a>
		</p>
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">{{ _('Name') }}</th>
					<th scope="col">{{ _('Permissions') }}</th>
				</tr>
			</thead>
			<tbody>
				{% for client in service.api_clients|sort(attribute='auth_username') %}
				<tr>
					<td>
						<a href="{{ url_for("service.api_show", service_id=service.id, id=client.id) }}">
							{{ client.auth_username }}
						</a>
					</td>
					<td>
						{% for perm in ['users', 'checkpassword', 'mail_aliases', 'remailer'] if client.has_permission(perm) %}
						{{ perm }}{{ ',' if not loop.last }}
						{% endfor %}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	{% endif %}

</div>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}