uffd/user/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, current_app

from uffd.navbar import register_navbar
from uffd.csrf import csrf_protect
from uffd.selfservice import send_passwordreset
from uffd.ldap import get_conn, escape_filter_chars
from uffd.session import login_required, is_valid_session, get_current_user

from .models import User, Group

bp_user = Blueprint("user", __name__, template_folder='templates', url_prefix='/user/')
@bp_user.before_request
@login_required()
def user_acl(): #pylint: disable=inconsistent-return-statements
	if not user_acl_check():
		flash('Access denied')
		return redirect(url_for('index'))

def user_acl_check():
	return is_valid_session() and get_current_user().is_in_group(current_app.config['ACL_ADMIN_GROUP'])

@bp_user.route("/")
@register_navbar('Users', icon='users', blueprint=bp_user, visible=user_acl_check)
def user_list():
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_USER"], '(objectclass=person)')
	users = []
	for i in conn.entries:
		users.append(User.from_ldap(i))
	return render_template('user_list.html', users=users)

@bp_user.route("/<int:uid>")
@bp_user.route("/new")
def user_show(uid=None):
	if not uid:
		user = User()
		ldif = '<none yet>'
	else:
		conn = get_conn()
		conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
		assert len(conn.entries) == 1
		user = User.from_ldap(conn.entries[0])
		ldif = conn.entries[0].entry_to_ldif()
	return render_template('user.html', user=user, user_ldif=ldif)

@bp_user.route("/<int:uid>/update", methods=['POST'])
@bp_user.route("/new", methods=['POST'])
@csrf_protect(blueprint=bp_user)
def user_update(uid=False):
	conn = get_conn()
	is_newuser = bool(not uid)
	if is_newuser:
		user = User()
		if not user.set_loginname(request.form['loginname']):
			flash('Login name does not meet requirements')
			return redirect(url_for('.user_show'))
	else:
		conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
		assert len(conn.entries) == 1
		user = User.from_ldap(conn.entries[0])
	if not user.set_mail(request.form['mail']):
		flash('Mail is invalide.')
		return redirect(url_for('.user_show'))
	new_displayname = request.form['displayname'] if request.form['displayname'] else request.form['loginname']
	if not user.set_displayname(new_displayname):
		flash('Display name does not meet requirements')
		return redirect(url_for('.user_show'))
	new_password = request.form.get('password')
	if new_password and not is_newuser:
		user.set_password(new_password)
	if user.to_ldap(new=is_newuser):
		if is_newuser:
			send_passwordreset(user.loginname)
			flash('User created. We sent the user a password reset link by mail')
		else:
			flash('User updated')
	else:
		flash('Error updating user: {}'.format(conn.result['message']))
	return redirect(url_for('.user_list'))

@bp_user.route("/<int:uid>/del")
@csrf_protect(blueprint=bp_user)
def user_delete(uid):
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_USER"], '(&(objectclass=person)(uidNumber={}))'.format((escape_filter_chars(uid))))
	assert len(conn.entries) == 1
	if conn.delete(conn.entries[0].entry_dn):
		flash('Deleted user')
	else:
		flash('Could not delete user: {}'.format(conn.result['message']))
	return redirect(url_for('.user_list'))

bp_group = Blueprint("group", __name__, template_folder='templates', url_prefix='/group/')
@bp_group.before_request
@login_required()
def group_acl(): #pylint: disable=inconsistent-return-statements
	if not user_acl_check():
		flash('Access denied')
		return redirect(url_for('index'))

@bp_group.route("/")
@register_navbar('Groups', icon='layer-group', blueprint=bp_group, visible=user_acl_check)
def group_list():
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_GROUPS"], '(objectclass=groupOfUniqueNames)')
	groups = []
	for i in conn.entries:
		groups.append(Group.from_ldap(i))
	return render_template('group_list.html', groups=groups)

@bp_group.route("/<int:gid>")
def group_show(gid):
	conn = get_conn()
	conn.search(current_app.config["LDAP_BASE_GROUPS"], '(&(objectclass=groupOfUniqueNames)(gidNumber={}))'.format((escape_filter_chars(gid))))
	assert len(conn.entries) == 1
	group = Group.from_ldap(conn.entries[0])
	return render_template('group.html', group=group)

uffd/views/user.py
import csv
import io

from flask import Blueprint, render_template, request, url_for, redirect, flash, current_app
from flask_babel import gettext as _, lazy_gettext
from sqlalchemy.exc import IntegrityError

from uffd.navbar import register_navbar
from uffd.csrf import csrf_protect
from uffd.remailer import forwarder, remailer
from uffd.database import db
from uffd.models import User, UserEmail, Role, MFAMethod
from .selfservice import send_passwordreset
from .session import login_required

bp = Blueprint("user", __name__, template_folder='templates', url_prefix='/user/')

bp.add_app_template_global(User, 'User')
bp.add_app_template_global(forwarder, 'forwarder')
bp.add_app_template_global(remailer, 'remailer')

def user_acl_check():
	return request.user and request.user.is_in_group(current_app.config['ACL_ADMIN_GROUP'])

@bp.before_request
@login_required(user_acl_check)
def user_acl():
	pass

@bp.route("/")
@register_navbar(lazy_gettext('Users'), icon='users', blueprint=bp, visible=user_acl_check)
def index():
	return render_template('user/list.html', users=User.query.all())

@bp.route("/<int:id>")
@bp.route("/new")
def show(id=None):
	user = User() if id is None else User.query.get_or_404(id)
	return render_template('user/show.html', user=user, roles=Role.query.all())

@bp.route("/new", methods=['POST'])
@csrf_protect(blueprint=bp)
def create():
	user = User()
	if request.form.get('serviceaccount'):
		user.is_service_user = True
	ignore_blocklist = request.form.get('ignore-loginname-blocklist', False)
	if not user.set_loginname(request.form['loginname'], ignore_blocklist=ignore_blocklist):
		flash(_('Login name does not meet requirements'))
		return redirect(url_for('user.show'))
	if not user.set_primary_email_address(request.form['email']):
		flash(_('E-Mail address is invalid'))
		return redirect(url_for('user.show'))
	new_displayname = request.form['displayname'] if request.form['displayname'] else request.form['loginname']
	if user.displayname != new_displayname and not user.set_displayname(new_displayname):
		flash(_('Display name does not meet requirements'))
		return redirect(url_for('user.show'))

	db.session.add(user)
	try:
		db.session.flush()
	except IntegrityError:
		flash(_('Login name or e-mail address is already in use'))
		return redirect(url_for('user.show'))

	for role in Role.query.all():
		if not user.is_service_user and role.is_default:
			continue
		if request.values.get('role-{}'.format(role.id), False):
			user.roles.append(role)
	user.update_groups()

	db.session.commit()
	if user.is_service_user:
		flash(_('Service user created'))
	else:
		send_passwordreset(user, new=True)
		flash(_('User created. We sent the user a password reset link by e-mail'))
	return redirect(url_for('user.show', id=user.id))

@bp.route("/<int:id>/update", methods=['POST'])
@csrf_protect(blueprint=bp)
def update(id):
	# pylint: disable=too-many-branches,too-many-statements
	user = User.query.get_or_404(id)

	for email in user.all_emails:
		if f'email-{email.id}-present' in request.form:
			email.verified = email.verified or (request.form.get(f'email-{email.id}-verified') == '1')
	for key, value in request.form.items():
		parts = key.split('-')
		if not parts[0] == 'newemail' or not parts[2] == 'address' or not value:
			continue
		tmp_id = parts[1]
		email = UserEmail(
			user=user,
			verified=(request.form.get(f'newemail-{tmp_id}-verified') == '1'),
		)
		if not email.set_address(value):
			flash(_('E-Mail address is invalid'))
			return redirect(url_for('user.show', id=id))
		db.session.add(email)

	try:
		db.session.flush()
	except IntegrityError:
		flash(_('E-Mail address already exists or is used by another account'))
		return redirect(url_for('user.show', id=id))

	verified_emails = UserEmail.query.filter_by(user=user, verified=True)
	user.primary_email = verified_emails.filter_by(id=request.form['primary_email']).one()
	if request.form['recovery_email'] == 'primary':
		user.recovery_email = None
	else:
		user.recovery_email = verified_emails.filter_by(id=request.form['recovery_email']).one()
	for service_user in user.service_users:
		if not service_user.has_email_preferences:
			continue
		value = request.form.get(f'service_{service_user.service.id}_email', 'primary')
		if value == 'primary':
			service_user.service_email = None
		else:
			service_user.service_email = verified_emails.filter_by(id=value).one()
	for email in user.all_emails:
		if request.form.get(f'email-{email.id}-delete') == '1':
			db.session.delete(email)

	new_displayname = request.form['displayname'] if request.form['displayname'] else request.form['loginname']
	if user.displayname != new_displayname and not user.set_displayname(new_displayname):
		flash(_('Display name does not meet requirements'))
		return redirect(url_for('user.show', id=id))
	new_password = request.form.get('password')
	if new_password:
		if not user.set_password(new_password):
			flash(_('Password is invalid'))
			return redirect(url_for('user.show', id=id))

	user.roles.clear()
	for role in Role.query.all():
		if not user.is_service_user and role.is_default:
			continue
		if request.values.get('role-{}'.format(role.id), False):
			user.roles.append(role)
	user.update_groups()

	db.session.commit()
	flash(_('User updated'))
	return redirect(url_for('user.show', id=user.id))

@bp.route('/<int:id>/deactivate')
@csrf_protect(blueprint=bp)
def deactivate(id):
	user = User.query.get_or_404(id)
	user.is_deactivated = True
	db.session.commit()
	flash(_('User deactivated'))
	return redirect(url_for('user.show', id=user.id))

@bp.route('/<int:id>/activate')
@csrf_protect(blueprint=bp)
def activate(id):
	user = User.query.get_or_404(id)
	user.is_deactivated = False
	db.session.commit()
	flash(_('User activated'))
	return redirect(url_for('user.show', id=user.id))

@bp.route('/<int:id>/mfa/disable')
@csrf_protect(blueprint=bp)
def disable_mfa(id):
	user = User.query.get_or_404(id)
	MFAMethod.query.filter_by(user=user).delete()
	user.update_groups()
	db.session.commit()
	flash(_('Two-factor authentication was reset'))
	return redirect(url_for('user.show', id=id))

@bp.route('/<int:id>/sessions/revoke')
@csrf_protect(blueprint=bp)
def revoke_sessions(id):
	user = User.query.get_or_404(id)
	user.sessions.clear()
	db.session.commit()
	flash(_('Sessions revoked'))
	return redirect(url_for('user.show', id=user.id))

@bp.route("/<int:id>/del")
@csrf_protect(blueprint=bp)
def delete(id):
	user = User.query.get_or_404(id)
	user.roles.clear()
	db.session.delete(user)
	db.session.commit()
	flash(_('Deleted user'))
	return redirect(url_for('user.index'))

@bp.route("/csv", methods=['POST'])
@csrf_protect(blueprint=bp)
def csvimport():
	csvdata = request.values.get('csv')
	if not csvdata:
		flash('No data for csv import!')
		return redirect(url_for('user.index'))

	ignore_blocklist = request.values.get('ignore-loginname-blocklist', False)

	roles = Role.query.filter_by(is_default=False).all()
	usersadded = 0
	with io.StringIO(initial_value=csvdata) as csvfile:
		csvreader = csv.reader(csvfile)
		for row in csvreader:
			if not len(row) == 3:
				flash("invalid line, ignored : {}".format(row))
				continue
			newuser = User()
			if not newuser.set_loginname(row[0], ignore_blocklist=ignore_blocklist) or not newuser.set_displayname(row[0]):
				flash("invalid login name, skipped : {}".format(row))
				continue
			if not newuser.set_primary_email_address(row[1]):
				flash("invalid e-mail address, skipped : {}".format(row))
				continue
			db.session.add(newuser)
			for role in roles:
				if str(role.id) in row[2].split(';'):
					role.members.append(newuser)
			newuser.update_groups()
			try:
				db.session.commit()
			except IntegrityError:
				flash('Error adding user {}'.format(row[0]))
				db.session.rollback()
				continue
			send_passwordreset(newuser, new=True)
			usersadded += 1
	flash('Added {} new users'.format(usersadded))
	return redirect(url_for('user.index'))

uffd/templates/user/list.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
	<div class="col">
		<p class="text-right">
			<a class="btn btn-primary" href="{{ url_for("user.show") }}">
				<i class="fa fa-plus" aria-hidden="true"></i> {{_("New")}}
			</a>
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#csvimport">
				<i class="fa fa-file-csv" aria-hidden="true"></i> {{_("CSV import")}}
			</button>
		</p>
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">{{_("UID")}}</th>
					<th scope="col">{{_("Login Name")}}</th>
					<th scope="col">{{_("Display Name")}}</th>
					<th scope="col">{{_("Roles")}}</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users|sort(attribute="unix_uid") %}
				<tr id="user-{{ user.id }}">
					<th scope="row">
						{{ user.unix_uid }}
					</th>
					<td>
						<a href="{{ url_for("user.show", id=user.id) }}">
							{{ user.loginname }}
						</a>
						{% if user.is_service_user %}
						<span class="badge badge-secondary">{{_('service')}}</span>
						{% endif %}
						{% if user.is_deactivated %}
						<span class="badge badge-danger">{{ _('deactivated') }}</span>
						{% endif %}
					</td>
					<td>
						{{ user.displayname }}
					</td>
					<td>
					{% for role in user.roles|sort(attribute="name") %}
						<a href="{{ url_for("role.show", roleid=role.id) }}">{{ role.name }}</a>{% if not loop.last %}, {% endif %}
					{% endfor %}
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<div class="modal fade" id="csvimport" tabindex="-1" role="dialog" aria-hidden="true">
	<form action="{{ url_for("user.csvimport") }}" method="POST">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">{{_("Import a csv formated list of users")}}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="{{_('Close')}}">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>
					{{_('The format should be "loginname,mailaddres,roleid1;roleid2". Neither setting the display name nor setting passwords is supported (yet). Example:')}}
				</p>
				<pre>
testuser1,foobar@example.com,5;2;6
testuser5,foobsdfar@example.com,
testuser5,foobadfar@example.com,0;5;2
testuser2,foobaadsfr@example.com,5;2
				</pre>
				<textarea rows="10" class="form-control" name="csv"></textarea>
				<div class="form-check mt-2">
					<input class="form-check-input" type="checkbox" id="ignore-loginname-blocklist" name="ignore-loginname-blocklist" value="1" aria-label="enabled">
					<label class="form-check-label" for="ignore-loginname-blocklist">{{_("Ignore login name blocklist")}}</label>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">{{_("Close")}}</button>
				<button type="submit" class="btn btn-primary">{{_("Import")}}</button>
			</div>
		</div>
	</div>
	</form>
</div>
{% endblock %}

uffd/templates/user/show.html
{% extends 'base.html' %}

{% macro new_email_row(tmp_id) %}
<tr>
	<td>
		<input class="form-control form-control-sm" type="email" name="newemail-{{ tmp_id }}-address" placeholder="{{ _('New address') }}">
	</td>
	<td class="text-center">
		<input type="checkbox" value="1" name="newemail-{{ tmp_id }}-verified">
	</td>
	<td class="text-center">
		<button type="button" class="btn btn-sm delete-new-email-row d-none"><i class="fas fa-times"></i></button>
	</td>
</tr>

{% endmacro %}

{% block body %}
{% if user.id %}
<form action="{{ url_for("user.update", id=user.id) }}" method="POST" autocomplete="off">
{% else %}
<form action="{{ url_for("user.create") }}" method="POST" autocomplete="off">
{% endif %}
<div class="align-self-center">
	{% if user.id and user.is_deactivated %}
	<div class="alert alert-warning">
		{{ _('This account is deactivated. The user cannot login and existing sessions are not usable. The user cannot log into services, but existing sessions on services might still be active.') }}
	</div>
	{% endif %}
	<div class="clearfix pb-2"><div class="float-sm-right">
		<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{_("Save")}}</button>
		<a href="{{ url_for("user.index") }}" class="btn btn-secondary">{{_("Cancel")}}</a>
		{% if user.id and not user.is_deactivated and user != request.user %}
			<a href="{{ url_for("user.deactivate", id=user.id) }}" class="btn btn-secondary">{{ _("Deactivate") }}</a>
		{% elif user.id and user.is_deactivated %}
			<a href="{{ url_for("user.activate", id=user.id) }}" class="btn btn-primary">{{ _("Activate") }}</a>
		{% else %}
			<a href="#" class="btn btn-secondary disabled">{{ _("Deactivate") }}</a>
		{% endif %}
		{% if user.id and user != request.user %}
			<a href="{{ url_for("user.delete", id=user.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});' class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> {{_("Delete")}}</a>
		{% else %}
			<a href="#" class="btn btn-danger disabled"><i class="fa fa-trash" aria-hidden="true"></i> {{_("Delete")}}</a>
		{% endif %}
	</div></div>
	<ul class="nav nav-tabs pt-2 border-0" id="tablist" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">{{_("Profile")}}</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" id="roles-tab" data-toggle="tab" href="#roles" role="tab" aria-controls="roles" aria-selected="false">{{_("Roles")}}</a>
		</li>
	</ul>
	<div class="tab-content border mb-2 pt-2" id="tabcontent">
		<div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="roles-tab">
			<div class="form-group col">
				<label for="user-uid">
					{{_('User ID')}}
					{% if user.is_service_user %}
					<span class="badge badge-secondary">{{_('service')}}</span>
					{% endif %}
				</label>
				{% if user.id %}
				<input type="number" class="form-control" id="user-uid" name="uid" value="{{ user.unix_uid }}" readonly>
				{% else %}
				<input type="text" class="form-control" id="user-uid" name="uid" placeholder="{{_('will be choosen')}}" readonly>
				{% endif %}
			</div>
			{% if not user.id %}
			<div class="form-group col">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" id="user-serviceaccount" name="serviceaccount" value="1" aria-label="enabled">
					<label class="form-check-label" for="user-serviceaccount">{{_('Service User')}}</label>
				</div>
			</div>
			{% endif %}
			<div class="form-group col">
				<label for="user-loginname">{{_("Login Name")}}</label>
				<input type="text" class="form-control" id="user-loginname" name="loginname" value="{{ user.loginname or '' }}" {% if user.id %}readonly{% endif %}>
				<small class="form-text text-muted">
					{{_("Only letters, numbers, dashes (\"-\") and underscores (\"_\") are allowed. At most 32, at least 2 characters. There is a word blocklist. Must be unique.")}}
				</small>
			</div>
			{% if not user.id %}
			<div class="form-group col">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" id="ignore-loginname-blocklist" name="ignore-loginname-blocklist" value="1" aria-label="enabled">
					<label class="form-check-label" for="ignore-loginname-blocklist">{{_('Ignore login name blocklist')}}</label>
				</div>
			</div>
			{% endif %}
			<div class="form-group col">
				<label for="user-loginname">{{_("Display Name")}}</label>
				<input type="text" class="form-control" id="user-displayname" name="displayname" value="{{ user.displayname or '' }}">
				<small class="form-text text-muted">
					{{_("If you leave this empty it will be set to the login name. At most 128, at least 2 characters. No character restrictions.")}}
				</small>
			</div>

			{% if not user.id %}
			<div class="form-group col">
				<label for="user-email">{{_("E-Mail Address")}}</label>
				<input type="email" class="form-control" id="user-email" name="email" value="">
				<small class="form-text text-muted">
					{{_("Make sure the address is correct! Services might use e-mail addresses as account identifiers and rely on them being unique and verified.")}}
				</small>
			</div>
			{% else %}
			<div class="form-group col">
				<span>{{_("E-Mail Addresses")}}</span>
				<table class="table table-sm mt-2">
					<thead>
						<tr>
							<th scope="col">{{_("Address")}}</th>
							<th scope="col" class="text-center">{{_("Verified")}}</th>
							<th scope="col" class="text-center">{{_("Delete")}}</th>
						</tr>
					</thead>
					<tbody id="email-rows">
						{% for email in user.all_emails %}
						<tr>
							<td>
								<input type="hidden" name="email-{{ email.id }}-present" value="1">
								{{ email.address }}
								{% if email == user.primary_email %}
								<span class="badge badge-primary">{{ _('primary') }}</span>
								{% endif %}
							</td>
							<td class="text-center">
								<input type="checkbox" value="1" name="email-{{ email.id }}-verified"{{ ' checked disabled' if email.verified }}>
							</td>
							<td class="text-center">
								<input type="checkbox" value="1" name="email-{{ email.id }}-delete"{{ ' disabled' if email == user.primary_email }}>
							</td>
						</tr>
						{% endfor %}
						{{ new_email_row(0) }}
					</tbody>
				</table>
				<small class="form-text text-muted">
					{{_("Make sure that addresses you add are correct! Services might use e-mail addresses as account identifiers and rely on them being unique and verified.")}}
				</small>
			</div>
			<div class="form-group col">
				<label>{{_("Primary E-Mail Address")}}</label>
				<select name="primary_email" class="form-control">
					{% for email in user.all_emails if email.verified %}
					<option value="{{ email.id }}"{{ ' selected' if email == user.primary_email }}>{{ email.address }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group col">
				<label>{{_("Recovery E-Mail Address")}}</label>
				<select name="recovery_email" class="form-control">
					<option value="primary"{{ ' selected' if not user.recovery_email }}>{{ _('Use primary address') }}</option>
					{% for email in user.all_emails if email.verified %}
					<option value="{{ email.id }}" {{ 'selected' if email == user.recovery_email }}>{{ email.address }}</option>
					{% endfor %}
				</select>
			</div>
			{% for service_user in user.service_users if service_user.has_email_preferences %}
			<div class="form-group col">
				<label>{{ _("Address for %(name)s", name=service_user.service.name) }}</label>
				<select name="service_{{ service_user.service.id }}_email" class="form-control">
					<option value="primary" {{ 'selected' if not service_user.service_email }}>{{ _('Use primary address') }}</option>
					{% for email in user.all_emails if email.verified %}
					<option value="{{ email.id }}" {{ 'selected' if email == service_user.service_email }}>{{ email.address }}</option>
					{% endfor %}
				</select>
			</div>
			{% endfor %}
			{% endif %}

			<div class="form-group col">
				<label for="user-loginname">{{_("Password")}}</label>
				{% if user.id %}
				<input type="password" autocomplete="new-password" class="form-control" id="user-password" name="password" placeholder="●●●●●●●●" minlength={{ User.PASSWORD_MINLEN }} maxlength={{ User.PASSWORD_MAXLEN }} pattern="{{ User.PASSWORD_REGEX }}">
				{% else %}
				<input type="text" class="form-control" id="user-password" name="password" placeholder="{{_("E-Mail to set it will be sent")}}" readonly>
				{% endif %}
				<small class="form-text text-muted">
					{{ User.PASSWORD_DESCRIPTION|safe }}
				</small>
			</div>

			{% if user.id %}
			<div class="form-group col">
				<div class="mb-1">{{_("Two-Factor Authentication")}}</div>
				<p>
					{{ _("Status:") }} {{ _("Enabled") if user.mfa_enabled else _("Disabled") }}<br>
					{{ user.mfa_recovery_codes|length }} {{ _("Recovery Codes") }}, {{ user.mfa_totp_methods|length }} {{ _("Authenticator Apps (TOTP)") }}, {{ user.mfa_webauthn_methods|length }} {{ _("U2F and FIDO2 Devices") }}
				</p>
				<a href="{{ url_for("user.disable_mfa", id=user.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});' class="btn btn-secondary">{{_("Reset 2FA")}}</a>
			</div>

			<div class="form-group col">
				<div class="mb-1">{{_("Sessions")}}</div>
				<p>{{ _("%(session_count)d active sessions", session_count=user.sessions|rejectattr('expired')|list|length) }}</p>
				<a href="{{ url_for("user.revoke_sessions", id=user.id) }}" onClick='return confirm({{_("Are you sure?")|tojson}});' class="btn btn-secondary">{{_("Revoke all sessions")}}</a>
			</div>

			{% endif %}

		</div>
		<div class="tab-pane fade" id="roles" role="tabpanel" aria-labelledby="roles-tab">
			<div class="form-group col">
				<span>{{_("Roles")}}:</span>
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th scope="col"></th>
							<th scope="col">{{_("Name")}}</th>
							<th scope="col">{{_("Description")}}</th>
						</tr>
					</thead>
					<tbody>
						{% for role in roles|sort(attribute="name") %}
						<tr id="role-{{ role.id }}">
							<td>
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="role-{{ role.id }}-checkbox" name="role-{{ role.id }}" value="1" aria-label="enabled"
										{% if user in role.members %}checked {% endif %}
										{% if role.is_default and not user.is_service_user %}disabled {% endif %}>
								</div>
							</td>
							<td>
								<a href="{{ url_for("role.show", roleid=role.id) }}">
									{{ role.name }}
								</a>
							</td>
							<td>
								{{ role.description }}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="form-group col">
				<span>{{_("Resulting groups (only updated after save)")}}:</span>
				<table class="table table-striped table-sm">
					<thead>
						<tr>
							<th scope="col">{{_("Name")}}</th>
							<th scope="col">{{_("Description")}}</th>
						</tr>
					</thead>
					<tbody>
						{% for group in user.groups|sort(attribute="name") %}
						<tr id="group-{{ group.id }}">
							<td>
								<a href="{{ url_for("group.show", id=group.id) }}">
									{{ group.name }}
								</a>
							</td>
							<td>
								{{ group.description }}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
</form>

<script>
$('#email-rows').on('click', '.delete-new-email-row', function () {
	$(this).closest('tr').remove()
});
let new_email_id = 1;
$('#email-rows').on('input', 'tr:last input', function () {
	$('#email-rows tr:last button.delete-new-email-row').removeClass('d-none');
	$('#email-rows').append({{ new_email_row('TMPID')|tojson }}.replace(/TMPID/g, new_email_id));
	new_email_id ++;
});
</script>

{% endblock %}