uffd/models/invite.py
import datetime

from flask_babel import gettext as _
from flask import current_app
from sqlalchemy import Column, String, Integer, ForeignKey, DateTime, Boolean
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import relationship

from uffd.utils import token_urlfriendly
from uffd.database import db
from .signup import Signup

invite_roles = db.Table('invite_roles',
	Column('invite_id', Integer(), ForeignKey('invite.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True),
	Column('role_id', Integer, ForeignKey('role.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
)

class Invite(db.Model):
	__tablename__ = 'invite'
	id = Column(Integer(), primary_key=True, autoincrement=True)
	token = Column(String(128), unique=True, nullable=False, default=token_urlfriendly)
	created = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
	creator_id = Column(Integer(), ForeignKey('user.id', onupdate='CASCADE'), nullable=True)
	creator = relationship('User')
	valid_until = Column(DateTime, nullable=False)
	single_use = Column(Boolean(create_constraint=True), default=True, nullable=False)
	allow_signup = Column(Boolean(create_constraint=True), default=True, nullable=False)
	used = Column(Boolean(create_constraint=True), default=False, nullable=False)
	disabled = Column(Boolean(create_constraint=True), default=False, nullable=False)
	roles = relationship('Role', secondary=invite_roles)
	signups = relationship('InviteSignup', back_populates='invite', lazy=True, cascade='all, delete-orphan')
	grants = relationship('InviteGrant', back_populates='invite', lazy=True, cascade='all, delete-orphan')

	@hybrid_property
	def expired(self):
		return self.valid_until < datetime.datetime.utcnow().replace(second=0, microsecond=0)

	@hybrid_property
	def voided(self):
		return self.single_use and self.used

	@property
	def permitted(self):
		if self.creator is None:
			return False # Creator does not exist (anymore)
		if self.creator.is_deactivated:
			return False
		if self.creator.is_in_group(current_app.config['ACL_ADMIN_GROUP']):
			return True
		if self.allow_signup and not self.creator.is_in_group(current_app.config['ACL_SIGNUP_GROUP']):
			return False
		for role in self.roles:
			if role.moderator_group is None or role.moderator_group not in self.creator.groups:
				return False
		return True

	@property
	def active(self):
		return not self.disabled and not self.voided and not self.expired and self.permitted

	@property
	def short_token(self):
		if len(self.token) < 30:
			return '<too short>'
		return self.token[:10] + '…'

	def disable(self):
		self.disabled = True

	def reset(self):
		self.disabled = False
		self.used = False

class InviteGrant(db.Model):
	__tablename__ = 'invite_grant'
	id = Column(Integer(), primary_key=True, autoincrement=True)
	invite_id = Column(Integer(), ForeignKey('invite.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
	invite = relationship('Invite', back_populates='grants')
	user_id = Column(Integer(), ForeignKey('user.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
	user = relationship('User')

	def apply(self):
		if not self.invite.active:
			return False, _('Invite link is invalid')
		if not self.invite.roles:
			return False, _('Invite link does not grant any roles')
		if set(self.invite.roles).issubset(self.user.roles):
			return False, _('Invite link does not grant any new roles')
		for role in self.invite.roles:
			self.user.roles.append(role)
		self.user.update_groups()
		self.invite.used = True
		return True, _('Success')

class InviteSignup(Signup):
	__tablename__ = 'invite_signup'
	id = Column(Integer(), ForeignKey('signup.id', onupdate='CASCADE', ondelete='CASCADE'), primary_key=True)
	invite_id = Column(Integer(), ForeignKey('invite.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
	invite = relationship('Invite', back_populates='signups')

	__mapper_args__ = {
		'polymorphic_identity': 'InviteSignup'
	}

	def validate(self):
		if not self.invite.active or not self.invite.allow_signup:
			return False, _('Invite link is invalid')
		return super().validate()

	def finish(self, password):
		if not self.invite.active or not self.invite.allow_signup:
			return None, _('Invite link is invalid')
		user, msg = super().finish(password)
		if user is not None:
			for role in self.invite.roles:
				user.roles.append(role)
			user.update_groups()
			self.invite.used = True
		return user, msg

uffd/views/invite.py
import datetime
import secrets

from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify, abort
from flask_babel import gettext as _, lazy_gettext, to_utc
import sqlalchemy

from uffd.csrf import csrf_protect
from uffd.sendmail import sendmail
from uffd.navbar import register_navbar
from uffd.database import db
from uffd.models import Role, User, Group, Invite, InviteSignup, InviteGrant, host_ratelimit, format_delay
from .session import login_required
from .signup import signup_ratelimit
from .selfservice import selfservice_acl_check

bp = Blueprint('invite', __name__, template_folder='templates', url_prefix='/invite/')

def invite_acl_check():
	if not request.user:
		return False
	if request.user.is_in_group(current_app.config['ACL_ADMIN_GROUP']):
		return True
	if request.user.is_in_group(current_app.config['ACL_SIGNUP_GROUP']):
		return True
	if Role.query.join(Role.moderator_group).join(Group.members).filter(User.id==request.user.id).count():
		return True
	return False

def view_acl_filter(user):
	if user.is_in_group(current_app.config['ACL_ADMIN_GROUP']):
		return sqlalchemy.true()
	creator_filter = (Invite.creator == user)
	rolemod_filter = Invite.roles.any(Role.moderator_group.has(Group.id.in_([group.id for group in user.groups])))
	return creator_filter | rolemod_filter

def reset_acl_filter(user):
	if user.is_in_group(current_app.config['ACL_ADMIN_GROUP']):
		return sqlalchemy.true()
	return Invite.creator == user

@bp.route('/')
@register_navbar(lazy_gettext('Invites'), icon='link', blueprint=bp, visible=invite_acl_check)
@login_required(invite_acl_check)
def index():
	invites = Invite.query.filter(view_acl_filter(request.user)).all()
	return render_template('invite/list.html', invites=invites)

@bp.route('/new')
@login_required(invite_acl_check)
def new():
	if request.user.is_in_group(current_app.config['ACL_ADMIN_GROUP']):
		allow_signup = True
		roles = Role.query.all()
	else:
		allow_signup = request.user.is_in_group(current_app.config['ACL_SIGNUP_GROUP'])
		roles = Role.query.join(Role.moderator_group).join(Group.members).filter(User.id==request.user.id).all()
	return render_template('invite/new.html', roles=roles, allow_signup=allow_signup)

def parse_datetime_local_input(value):
	return to_utc(datetime.datetime.fromisoformat(value))

@bp.route('/new', methods=['POST'])
@login_required(invite_acl_check)
@csrf_protect(blueprint=bp)
def new_submit():
	invite = Invite(creator=request.user,
	                single_use=(request.values['single-use'] == '1'),
	                valid_until=parse_datetime_local_input(request.values['valid-until']),
	                allow_signup=(request.values.get('allow-signup', '0') == '1'))
	for key, value in request.values.items():
		if key.startswith('role-') and value == '1':
			invite.roles.append(Role.query.get(key[5:]))
	if invite.valid_until > datetime.datetime.utcnow() + datetime.timedelta(days=current_app.config['INVITE_MAX_VALID_DAYS']):
		flash(_('The "Expires After" date is too far in the future'))
		return new()
	if not invite.permitted:
		flash(_('You are not allowed to create invite links with these permissions'))
		return new()
	if not invite.allow_signup and not invite.roles:
		flash(_('Invite link must either allow signup or grant at least one role'))
		return new()
	db.session.add(invite)
	db.session.commit()
	return redirect(url_for('invite.index'))

@bp.route('/<int:invite_id>/disable', methods=['POST'])
@login_required(invite_acl_check)
@csrf_protect(blueprint=bp)
def disable(invite_id):
	invite = Invite.query.filter(view_acl_filter(request.user)).filter_by(id=invite_id).first_or_404()
	invite.disable()
	db.session.commit()
	return redirect(url_for('.index'))

@bp.route('/<int:invite_id>/reset', methods=['POST'])
@login_required(invite_acl_check)
@csrf_protect(blueprint=bp)
def reset(invite_id):
	invite = Invite.query.filter(reset_acl_filter(request.user)).filter_by(id=invite_id).first_or_404()
	invite.reset()
	db.session.commit()
	return redirect(url_for('.index'))

@bp.route('/<int:invite_id>/<token>')
def use(invite_id, token):
	invite = Invite.query.get(invite_id)
	if not invite or not secrets.compare_digest(invite.token, token):
		abort(404)
	if not invite.active:
		flash(_('Invalid invite link'))
		return redirect('/')
	return render_template('invite/use.html', invite=invite)

@bp.route('/<int:invite_id>/<token>/grant', methods=['POST'])
@login_required(selfservice_acl_check)
@csrf_protect(blueprint=bp)
def grant(invite_id, token):
	invite = Invite.query.get(invite_id)
	if not invite or not secrets.compare_digest(invite.token, token):
		abort(404)
	invite_grant = InviteGrant(invite=invite, user=request.user)
	db.session.add(invite_grant)
	success, msg = invite_grant.apply()
	if not success:
		flash(msg)
		return redirect(url_for('selfservice.index'))
	db.session.commit()
	flash(_('Roles successfully updated'))
	return redirect(url_for('selfservice.index'))

@bp.url_defaults
def inject_invite_token(endpoint, values):
	if endpoint in ['invite.signup_submit', 'invite.signup_check']:
		if 'invite_id' in request.view_args:
			values['invite_id'] = request.view_args['invite_id']
		if 'token' in request.view_args:
			values['token'] = request.view_args['token']

@bp.route('/<int:invite_id>/<token>/signup')
def signup_start(invite_id, token):
	invite = Invite.query.get(invite_id)
	if not invite or not secrets.compare_digest(invite.token, token):
		abort(404)
	if not invite.active:
		flash(_('Invalid invite link'))
		return redirect('/')
	if not invite.allow_signup:
		flash(_('Invite link does not allow signup'))
		return redirect('/')
	return render_template('signup/start.html')

@bp.route('/<int:invite_id>/<token>/signupcheck', methods=['POST'])
def signup_check(invite_id, token):
	if host_ratelimit.get_delay():
		return jsonify({'status': 'ratelimited'})
	host_ratelimit.log()
	invite = Invite.query.get(invite_id)
	if not invite or not secrets.compare_digest(invite.token, token):
		abort(404)
	if not invite.active or not invite.allow_signup:
		return jsonify({'status': 'error'}), 403
	if not User().set_loginname(request.form['loginname']):
		return jsonify({'status': 'invalid'})
	if User.query.filter_by(loginname=request.form['loginname']).all():
		return jsonify({'status': 'exists'})
	return jsonify({'status': 'ok'})

@bp.route('/<int:invite_id>/<token>/signup', methods=['POST'])
def signup_submit(invite_id, token):
	invite = Invite.query.get(invite_id)
	if not invite or not secrets.compare_digest(invite.token, token):
		abort(404)
	if request.form['password1'] != request.form['password2']:
		flash(_('Passwords do not match'), 'error')
		return render_template('signup/start.html')
	signup_delay = signup_ratelimit.get_delay(request.form['mail'])
	host_delay = host_ratelimit.get_delay()
	if signup_delay and signup_delay > host_delay:
		flash(_('Too many signup requests with this mail address! Please wait %(delay)s.',
		        delay=format_delay(signup_delay)), 'error')
		return render_template('signup/start.html')
	if host_delay:
		flash(_('Too many requests! Please wait %(delay)s.', delay=format_delay(host_delay)), 'error')
		return render_template('signup/start.html')
	host_ratelimit.log()
	signup = InviteSignup(invite=invite, loginname=request.form['loginname'],
	                      displayname=request.form['displayname'],
	                      mail=request.form['mail'],
	                      password=request.form['password1'])
	valid, msg = signup.validate()
	if not valid:
		flash(msg, 'error')
		return render_template('signup/start.html')
	db.session.add(signup)
	db.session.commit()
	sent = sendmail(signup.mail, 'Confirm your mail address', 'signup/mail.txt', signup=signup)
	if not sent:
		flash(_('Could not send mail'), 'error')
		return render_template('signup/start.html')
	signup_ratelimit.log(request.form['mail'])
	return render_template('signup/submitted.html', signup=signup)

uffd/templates/invite/list.html
{% extends 'base.html' %}

{% block body %}

<div class="btn-toolbar mb-2">
	<a class="btn btn-primary ml-auto" href="{{ url_for("invite.new") }}"><i class="fa fa-plus" aria-hidden="true"></i> {{_('New')}}</a>
</div>
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">{{_('Link')}}</th>
				<th scope="col">{{_('Created by')}}</th>
				<th scope="col">{{_('Permissions')}}</th>
				<th scope="col">{{_('Usages')}}</th>
				<th scope="col">{{_('Status')}}</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			{% for invite in invites|sort(attribute='created', reverse=True)|sort(attribute='active', reverse=True) %}
			<tr>
				<td>
					{% if invite.creator == request.user and invite.active %}
					<a href="{{ url_for('invite.use', invite_id=invite.id, token=invite.token) }}"><code>{{ invite.short_token }}</code></a>
					<button type="button" class="btn btn-link btn-sm p-0 copy-clipboard" data-copy="{{ url_for('invite.use', invite_id=invite.id, token=invite.token, _external=True) }}" title="{{_('Copy link to clipboard')}}"><i class="fas fa-clipboard"></i></button>
					<button type="button" class="btn btn-link btn-sm p-0" data-toggle="modal" data-target="#modal-{{ invite.id }}-qrcode" title="{{_('Show link as QR code')}}"><i class="fas fa-qrcode"></i></button>
					{% else %}
					<code>{{ invite.short_token }}</code>
					{% endif %}
				</td>
				<td>
					{% if not invite.creator %}
						{{ '<deleted user>' }}
					{% else %}
						{{ invite.creator.loginname }}
					{% endif %}
				</td>
				<td>
					{{ _('Signup') if invite.allow_signup }}{{ ', ' if invite.allow_signup and invite.roles }}
					{% for role in invite.roles %}{{ ', ' if loop.index != 1 }}<i class="fas fa-key"></i>&thinsp;{{ role.name }}{% endfor %}
				</td>
				<td>
					<span style="white-space: nowrap;">{{ invite.signups|selectattr('completed')|list|length }} <i class="fas fa-users" title="{{ _('user signups') }}"></i></span>,
					<span style="white-space: nowrap;">{{ invite.grants|length }} <i class="fas fa-key" title="role grants"></i></span>
				</td>
				<td>
					{% if invite.disabled %}
						{{_('Disabled')}}
					{% elif invite.voided %}
						{{_('Voided')}}
					{% elif invite.expired %}
						{{_('Expired')}}
					{% elif not invite.permitted %}
						{{_('Invalid, unpermitted creator')}}
					{% elif not invite.active %}
						{{_('Invalid')}}
					{% elif invite.single_use %}
						{{ _('Valid once, expires %(expiry_date)s', expiry_date=invite.valid_until|dateformat) }}
					{% else %}
						{{ _('Valid, expires %(expiry_date)s', expiry_date=invite.valid_until|dateformat) }}
					{% endif %}
				</td>
				<td class="text-right">
					<button type="button" class="btn btn-link btn-sm p-0" data-toggle="modal" data-target="#modal-{{ invite.id }}"><i class="fas fa-ellipsis-h"></i></button>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% for invite in invites %}
<div class="modal" tabindex="-1" id="modal-{{ invite.id }}">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">{{_('Invite Link Details')}}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<ul class="list-unstyled">
					<li><b>{{_('Type:')}}</b> {% if invite.single_use %}{{_('Single-use')}}{% else %}{{_('Multi-use')}}{% endif %}</li>
					<li><b>{{_('Created:')}}</b> {{ invite.created|datetimeformat }}</li>
					<li><b>{{_('Expires:')}}</b> {{ invite.valid_until|datetimeformat }}</li>
					<li><b>{{_('Permissions:')}}</b>
						<ul>
							{% if invite.allow_signup %}
							<li>{{_('Link allows account registration')}}</li>
							{% else %}
							<li>{{_('No account registration allowed')}}</li>
							{% endif %}
							{% for role in invite.roles %}
							<li>{{_('Link grants users the role "%(name)s"', name=role.name)}}</li>
							{% endfor %}
						</ul>
					</li>
					<li><b>Usages:</b>
						{% if not invite.signups and not invite.grants %}
						{{_('Never used')}}
						{% else %}
						<ul>
							{% for signup in invite.signups if signup.completed %}
							<li>{{_('Registration of user <a href="%(user_url)s">%(user_name)s</a>', user_url=url_for('user.show', id=signup.user.id)|e, user_name=signup.user.loginname|e)|safe}}</li>
							{% endfor %}
							{% for grant in invite.grants if grant.user %}
							<li>{{_('Roles granted to <a href="%(user_url)s">%(user_name)s</a>', user_url=url_for('user.show', id=grant.user.id)|e, user_name=grant.user.loginname|e)|safe}}</li>
							{% endfor %}
						</ul>
						{% endif %}
					</li>
				</ul>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				{% if invite.active %}
				<form action="{{ url_for('invite.disable', invite_id=invite.id) }}" method="POST">
				<button type="submit" class="btn btn-primary">{{_('Disable Link')}}</button>
				</form>
				{% elif invite.creator == request.user and not invite.expired and invite.permitted %}
				<form action="{{ url_for('invite.reset', invite_id=invite.id) }}" method="POST">
				<button type="submit" class="btn btn-primary">{{_('Reenable Link')}}</button>
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endfor %}

{% for invite in invites if invite.creator == request.user %}
<div class="modal" tabindex="-1" id="modal-{{ invite.id }}-qrcode">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">{{_('Invite')}}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				{{ url_for('invite.use', invite_id=invite.id, token=invite.token, _external=True)|qrcode_svg(width='100%', height='100%') }}
			</div>
		</div>
	</div>
</div>
{% endfor %}

<script>
$(".copy-clipboard").on("click", function() {
	navigator.clipboard.writeText($(this).data("copy"));
});
</script>
{% endblock %}

uffd/templates/invite/new.html
{% extends 'base.html' %}

{% block body %}
<form action="{{ url_for("invite.new_submit") }}" method="POST" autocomplete="off" class="form">
	<div class="form-group">
		<label for="single-use">{{_('Link Type')}}</label>
		<select class="form-control" id="single-use" name="single-use">
			<option value="1" {{ 'selected' if request.values.get('single-use', '1') == '1' }}>{{_('Valid for a single successful use')}}</option>
			<option value="0" {{ 'selected' if request.values.get('single-use', '1') == '0' }}>{{_('Multi-use')}}</option>
		</select>
	</div>
	<div class="form-group">
		<label for="valid-until">{{_('Valid Until')}}</label>
		<input class="form-control" type="datetime-local" id="valid-until" name="valid-until" value="{{ request.values.get('valid-until') or (datetime.now() + timedelta(hours=36)).replace(hour=23, minute=59).isoformat(timespec='minutes') }}" min="{{ datetime.now().isoformat(timespec='minutes') }}" max="{{ (datetime.now() + timedelta(days=config['INVITE_MAX_VALID_DAYS'])).isoformat(timespec='minutes') }}">
		<small class="text-muted">{{_('Must be within the next %(max_valid_days)d days', max_valid_days=config['INVITE_MAX_VALID_DAYS'])}}</small>
	</div>
	{% if allow_signup %}
	<div class="form-group">
		<label for="allow-signup">{{_('Account Registration')}}</label>
		<select class="form-control" id="allow-signup" name="allow-signup">
			<option value="1" {{ 'selected' if request.values.get('allow-signup', '1') == '1' }}>{{_('Link allows account registration')}}</option>
			<option value="0" {{ 'selected' if request.values.get('allow-signup', '1') == '0' }}>{{_('No account registration allowed')}}</option>
		</select>
	</div>
	{% else %}
	<input type="hidden" name="allow-signup" value="0">
	{% endif %}
	{% if roles %}
	<div class="form-group">
		<label for="valid-until">{{_('Granted Roles')}}</label>
		<table class="table table-sm">
			<thead>
				<tr>
					<th scope="col"></th>
					<th scope="col">{{_('Name')}}</th>
					<th scope="col">{{_('Description')}}</th>
				</tr>
			</thead>
			<tbody>
				{% for role in roles|sort(attribute="name") if not role.is_default %}
				<tr>
					<td>
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="role-{{ role.id }}" name="role-{{ role.id }}" value="1" {{ 'checked' if 'role-%d'%role.id in request.values }}>
						</div>
					</td>
					<td>{{ role.name }}</td>
					<td>{{ role.description }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	{% endif %}
	<button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> {{_('Create Link')}}</button>
	<a href="{{ url_for("invite.index") }}" class="btn btn-secondary">{{_('Cancel')}}</a>
</form>
{% endblock %}

uffd/templates/invite/use.html
{% extends 'base_narrow.html' %}

{% block body %}
	<div class="col-12 mb-3">
		<h2 class="text-center">{{_('Invite Link')}}</h2>
	</div>
	{% if not request.user %}
	<p>{{_('Welcome to the %(org_name)s Single-Sign-On!', org_name=config.ORGANISATION_NAME)}}</p>
	{% endif %}

	{% if invite.roles and invite.allow_signup %}
	<p>{{_('With this link you can register a new user account with the following roles or add the roles to an existing account:')}}</p>
	{% elif invite.roles %}
	<p>{{_('With this link you can add the following roles to an existing account:')}}</p>
	{% elif invite.allow_signup %}
	<p>{{_('With this link you can register a new user account.')}}</p>
	{% endif %}
	{% if invite.roles %}
	<ul>
		{% for role in invite.roles %}
		<li>{{ role.name }}{% if role.description %}: {{ role.description }}{% endif %}</li>
		{% endfor %}
	</ul>
	{% endif %}
	{% if request.user %}
		{% if invite.roles %}
			<form method="POST" action="{{ url_for("invite.grant", invite_id=invite.id, token=invite.token) }}" class="mb-2">
				<button type="submit" class="btn btn-primary btn-block">{{_('Add the roles to your account now')}}</button>
			</form>
			<a href="{{ url_for("session.logout", ref=url_for("session.login", ref=request.full_path)) }}" class="btn btn-secondary btn-block">{{_('Logout and switch to a different account')}}</a>
		{% endif %}
		{% if invite.allow_signup %}
			<a href="{{ url_for("session.logout", ref=url_for("invite.signup_start", invite_id=invite.id, token=invite.token)) }}" class="btn btn-secondary btn-block">{{_('Logout to register a new account')}}</a>
		{% endif %}
	{% else %}
		{% if invite.allow_signup %}
			<a href="{{ url_for("invite.signup_start", invite_id=invite.id, token=invite.token) }}" class="btn btn-primary btn-block">{{_('Register a new account')}}</a>
		{% endif %}
		{% if invite.roles %}
			<a href="{{ url_for("session.login", ref=request.full_path) }}" class="btn btn-primary btn-block">{{_('Login and add the roles to your account')}}</a>
		{% endif %}
	{% endif %}
{% endblock %}